# Generated by Django 3.2.9 on 2021-11-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizes'},
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
