# Generated by Django 3.2.9 on 2021-11-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20211125_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_1',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_2',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_3',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_4',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
