# Generated by Django 3.2.9 on 2021-12-08 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_question_choice_4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quiz.quiz'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id', models.IntegerField(max_length=1)),
                ('choice', models.CharField(max_length=255)),
                ('is_correct_answer', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='quiz.question')),
            ],
        ),
    ]
