# Generated by Django 3.2.9 on 2021-12-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20211208_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('quiz', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_id',
            field=models.IntegerField(),
        ),
    ]
